# Generated by Django 5.0.6 on 2024-07-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listbuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
